name = "Vaalosbasicspeedsetup"
author = "vaalo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f625dbbb94bf2a8d2cd2de2539d7c1c897262e13d2ed995f346964a31a939275"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.2"]
